"""add qtd_comunicados ao condominio

Revision ID: 30a771e00051
Revises: d9844f5a3ed5
Create Date: 2026-05-18 21:27:29.505497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a771e00051'
down_revision = 'd9844f5a3ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condominios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qtd_comunicados', sa.Integer(), nullable=False, server_default='3'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condominios', schema=None) as batch_op:
        batch_op.drop_column('qtd_comunicados')

    # ### end Alembic commands ###
