"""add funil gep na reserva

Revision ID: 31adf7e952ce
Revises: 30a771e00051
Create Date: 2026-05-20 00:44:53.791422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31adf7e952ce'
down_revision = '30a771e00051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boleto_gerado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('boleto_enviado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('boleto_pago', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_column('boleto_pago')
        batch_op.drop_column('boleto_enviado')
        batch_op.drop_column('boleto_gerado')

    # ### end Alembic commands ###
