"""add comunicados_salao ao condominio

Revision ID: d9844f5a3ed5
Revises: c3d4e5f6a7b8
Create Date: 2026-05-18 20:43:25.561513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9844f5a3ed5'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condominios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comunicados_salao', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condominios', schema=None) as batch_op:
        batch_op.drop_column('comunicados_salao')

    # ### end Alembic commands ###
