"""make_enc_columns_nullable_for_lgpd_erasure

Revision ID: dd197b4a9d23
Revises: 307e5477dda4
Create Date: 2026-05-14 10:15:13.895479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd197b4a9d23'
down_revision = '307e5477dda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.alter_column('_nome_solicitante_enc',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('_apartamento_enc',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.alter_column('_apartamento_enc',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('_nome_solicitante_enc',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
